# .travis.yml for travis-ci.org 
#
# Test configuration:
# - cli          : travis lint ./.travis.yml

language: python

python:
  - '3.5'

branches:
  only:
    - master
    
script:
  - ./test/test.sh
